### ISSUE TITLE
Should README suggest squashing commits?

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/cppbestpractices#17]
Merging future commits would bring in all commits, so it makes more sense to simply start a new repo with the entire history.

**Comment by adrienthebo** [comment]
@MikaelSmith I assume this is for the cpp-project-template repo. If that's the case, I think we would be better off pushing shared code (where possible) into a different library such as leatherman. Trying to cherry-pick/merge commits from a shared template repo into instatiations of that template is likely bound to introduce all sorts of merge conflicts.

What kind of CI changes were you thinking of?

**Comment by MikaelSmith** [comment]
Yeah, meant for cpp-project-template.

Travis and AppVeyor config essentially. Although there may eventually be ways to simplify those with Ubuntu 14.04 (Travis) and MSYS2 (AppVeyor).

I find I have to occasionally fix up CI configs, and doing it once then merging to other projects is convenient.

**Comment by adrienthebo** [comment]
For syncing common files like appveyor and travis.yml across multiple repositories https://github.com/puppet-community/modulesync might be useful - it was originally built for modules but it's trying to solve the same problem.

**Comment by MikaelSmith** [comment]
Concluding no, the necessary changes in the future should be minor and keeping all the commit history is ugly.
