### ISSUE TITLE
Add examples of Unicode handling using utfcpp

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/cppbestpractices#7]
http://utfcpp.sourceforge.net/ is a useful library for UTF-8 handling in C++. We should add it to Leatherman, and provide examples here.

**Comment by MikaelSmith** [comment]
Also run it past RelEng.

**Comment by MikaelSmith** [comment]
Roled into #5.

**Comment by kylog** [comment]
Is this overtaken by events or still applicable?

**Comment by peterhuene** [comment]
The native compiler no longer uses it, so if there is no other need for it from other libraries, then we can properly close this.  The native compiler uses ICU for full Unicode support in the Puppet language.

**Comment by MikaelSmith** [comment]
This might be useful for cpp-hocon. As a general library, not sure. I'll close it.
